### ISSUE TITLE
Pentaho-mongodb-plugin is not working with mongodb version 3.0.1 and java driver version 2.13

### ISSUE THREAD

**Issue by ammarkhalid** [pentaho/pentaho-mongodb-plugin#98]
Hi,
  We were previously using mongodb 2.6 and java mongodb driver version was 2.11.1. But now we have updated mongodb version to 3.0.1 and java driver to 2.13 for compatibility purposes. Kindly can you provide an update on when we can expect latest version of pentaho-mongodb-plugin?

Note*: We are currently facing an error "Can not open connection with same db twice".

**Comment by mattyb149** [comment]
Please use the forums (forums.pentaho.com) to ask questions. In this case I believe it is slated for the upcoming 5.4 release, but I wouldn't swear to it :)

**Comment by ammarkhalid** [comment]
Kindly if you can provide any tentative dates of upcoming 5.4 release?

**Comment by mattyb149** [comment]
I believe the official release date is June 9, 2015
